name: CLA Listener

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  call-central-bot:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'I have read the CLA Document and I hereby sign the CLA') }}
    
    uses: scienting/cla/.github/workflows/cla-sign.yml@main

    secrets:
      CLA_BOT_PAT: ${{ secrets.CLA_BOT_PAT }}
